### PR TITLE
test: switch to vitest

### PR DESCRIPTION
**Pull request by uncenter**
This PR migrates the project from `mocha` + `chai` + `c8` to [`vitest`](https://vitest.dev/). The tests are passing right now but there is an issue with an error in the circular JSON test on lines 357-371... still working that out. See image below:

Screenshot 2024-01-01 at 23 18 09 (Code)

You can run tests with `npm run vitest` command.

### CODE REVIEW

**Comment by uncenter** [comment]
Still haven't figured out the circular error but everything else is working...

**Comment by uncenter** [comment]
This doesn't seem to be at all related to `vitest` and just some other issue that snuck by in previous testing?
Trying running the following code in the root directory of the flat-cache repository:

```js
// index.js
const fc = require('./src/cache.js');
const utils = require('./src/utils');
const path = require('path');

const cache = fc.load('someId');

const data = {
  foo: 'foo',
  bar: 'bar',
};

data.circular = data;

cache.setKey('some-key', data);
cache.getKey('some-key');

cache.save();
utils.readJSON(path.resolve(__dirname, './.cache/someId'))['some-key'];
```

**Comment by jaredwray** [comment]
@uncenter - to you plan to do this? If not, we can wait on it as most likely I would move this to AVA.

**Comment by uncenter** [comment]
This should have been good to merge, I'm not sure why that circular JSON thing is an issue. It isn't related to vitest at all.

**Comment by uncenter** [comment]
I could tell it to `--dangerouslyIgnoreUnhandledErrors` for now? Not sure if that is a solution you would feel comfortable with. Ideally we should fix the root cause of the error first.

**Comment by jaredwray** [comment]
@uncenter - going to close this and will ping you as we are going to be migrating this in the coming months to cacheable as a package and will rewrite it in typescript with async.

**Comment by uncenter** [comment]
> This doesn't seem to be at all related to `vitest` and just some other issue that snuck past previous testing? Trying running the following code in the root directory of the flat-cache repository:
> 
> ```js
> // index.js
> const fc = require('./src/cache.js');
> const utils = require('./src/utils');
> const path = require('path');
> 
> const cache = fc.load('someId');
> 
> const data = {
>   foo: 'foo',
>   bar: 'bar',
> };
> 
> data.circular = data;
> 
> cache.setKey('some-key', data);
> cache.getKey('some-key');
> 
> cache.save();
> utils.readJSON(path.resolve(__dirname, './.cache/someId'))['some-key'];
> ```
> 
> You'll get the same error I was seeing through Vitest. I haven't changed any internals, just the tests, which is something to note.

Should I create an issue for this?

**Comment by jaredwray** [comment]
Nope as we will be doing a full rewrite and port it to this mono repo in the upcoming months. We will also bump the version as we will most likely move to async and await for the calls.

**Comment by uncenter** [comment]
> Nope as we will be doing a full rewrite and port it to this mono repo in the upcoming months. We will also bump the version as we will most likely move to async and await for the calls.

Sweet! Good luck with the rewrite.

**Comment by jaredwray** [comment]
Yep! If you want to help I will ping you when we start it. Just let me know

**Pull request closed without merging**
