### PR TITLE
Classify

### PR DESCRIPTION
**Pull request by jimmywarting**

### CODE REVIEW

**Comment by jaredwray** [comment]
Hi @jimmywarting - thanks for the pull request and this is a pretty big change. How can we ensure that it is compatible with previous versions as we want to make sure.

**Comment by jimmywarting** [comment]
The tests remain unchanged, as they continue to pass even with the introduction of new code.

The incorporation of classes into NodeJS dates back to version 6.0.0, as documented here: [classes @ MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#browser_compatibility).

Furthermore, your project already specifies an engine version greater than 10
https://github.com/jaredwray/flat-cache/blob/5203e8e8e4e606051defc3ef799d47797386eff9/package.json#L17-L19

Given these factors, it seems unlikely that any significant disruptive changes or extensive patches will be necessary. The functionality remains the same.

**Comment by jimmywarting** [comment]
Also, following the jsdoc [guideline](https://jsdoc.app/tags-param.html) ensure better/prober IDE suggestion and better helps out with folks who like to use typescript and for those who like to use vanilla javascript without having to write typescript syntax.

**Comment by jaredwray** [comment]
@jimmywarting - thanks for the explanation. Looks like some of the linting failed. Can you get that fixed?

**Comment by jaredwray** [comment]
@jimmywarting going to close this out and start the new version which will be 4.x.x. This will be classify and in typescript with Keyv backing it. Would you like to work on the project with me? If so, we can do a call and discuss or email.

**Comment by jimmywarting** [comment]
if it's going to be rewritten into typescript then i will pass. 
i write types without typescript so i don't have to compile stuff.

- https://www.dandoescode.com/blog/using-typescript-without-typescript
- https://www.puruvj.dev/blog/get-to-know-typescript--using-typescript-without-typescript
- https://blog.mact.me/2020/12/12/typescript-without-typescript
- [svelte is replacing TS with JSDoc](https://www.youtube.com/watch?v=MJHO6FSioPI)

even wrote my own [You might not need typescript](https://jimmywarting.github.io/you-might-not-need-typescript)

**Pull request closed without merging**
